export const bookings = [
    {
      date: "01/08/2025",
      days: 2,
      name: "Ajmal Khan",
      address: "Hosur road, Anekal Bangalore",
      phone: "8892364643",
      alternative_phone: "9448735823",
      event_type: "Wedding",
      religion: "Muslim",
      timings: "6:00 PM to 6:00PM",
      services: {
        hallRent: true,
        cookingUtensils: false,
        mantap: false,
        darbarChairs: true,
        cleaningLabour: true,
        deepaLamps: false,
        orchestraStage: false,
        dolStage: true,
        peta: false,
        redCarpet: true,
        micSet: true,
        decorPlants: true,
        godStatues: false,
        holigeDosaStove: false,
        lightDecoration: true,
        roadCuttingSerialSet: true,
        lightMusic: true,
        hasemani: false,
        speakers: true,
        chairCovers: true,
      },
    },
    {
      date: "08/08/2025",
      days: 1,
      name: "Tanveer Khan",
      address: "Banhadurpur, Anekal Bangalore",
      phone: "8892364643",
      alternative_phone: "9448735823",
      event_type: "Reception",
      religion: "Muslim",
      timings: "6:00 PM to 12:00AM",
      services: {
        hallRent: true,
        cookingUtensils: false,
        mantap: false,
        darbarChairs: true,
        cleaningLabour: true,
        deepaLamps: false,
        orchestraStage: false,
        dolStage: true,
        peta: false,
        redCarpet: true,
        micSet: true,
        decorPlants: true,
        godStatues: false,
        holigeDosaStove: false,
        lightDecoration: true,
        roadCuttingSerialSet: true,
        lightMusic: true,
        hasemani: false,
        speakers: true,
        chairCovers: true,
      },
    },
    {
      date: "08/09/2025",
      days: 1,
      name: "Tanveer Khan",
      address: "Attebele Bangalore",
      phone: "8892364643",
      alternative_phone: "9448735823",
      event_type: "Engagement",
      religion: "Muslim",
      timings: "12:00 PM to 11:59PM",
      services: {
        hallRent: true,
        cookingUtensils: false,
        mantap: false,
        darbarChairs: true,
        cleaningLabour: true,
        deepaLamps: false,
        orchestraStage: false,
        dolStage: true,
        peta: false,
        redCarpet: true,
        micSet: true,
        decorPlants: true,
        godStatues: false,
        holigeDosaStove: false,
        lightDecoration: true,
        roadCuttingSerialSet: true,
        lightMusic: true,
        hasemani: false,
        speakers: true,
        chairCovers: true,
      },
    },
    {
      date: "02/09/2025",
      days: 2,
      name: "Srinivasapp",
      address: "Vanknahalli, Anekal, Bangalore",
      phone: "8892364643",
      alternative_phone: "9448735823",
      event_type: "Wedding",
      religion: "Hindu",
      timings: "6:00 PM to 6:00PM",
      services: {
        hallRent: true,
        cookingUtensils: false,
        mantap: false,
        darbarChairs: true,
        cleaningLabour: true,
        deepaLamps: false,
        orchestraStage: false,
        dolStage: true,
        peta: false,
        redCarpet: true,
        micSet: true,
        decorPlants: true,
        godStatues: false,
        holigeDosaStove: false,
        lightDecoration: true,
        roadCuttingSerialSet: true,
        lightMusic: true,
        hasemani: false,
        speakers: true,
        chairCovers: true,
      },
    },
    {
      date: "31/10/2025",
      days: 2,
      name: "Raju Gowda",
      address: "Hompelghatta, Anekal, Bangalore",
      phone: "8892364643",
      alternative_phone: "9448735823",
      event_type: "Wedding",
      religion: "Hindu",
      timings: "6:00 PM to 6:00PM",
      services: {
        hallRent: true,
        cookingUtensils: false,
        mantap: false,
        darbarChairs: true,
        cleaningLabour: true,
        deepaLamps: false,
        orchestraStage: false,
        dolStage: true,
        peta: false,
        redCarpet: true,
        micSet: true,
        decorPlants: true,
        godStatues: false,
        holigeDosaStove: false,
        lightDecoration: true,
        roadCuttingSerialSet: true,
        lightMusic: true,
        hasemani: false,
        speakers: true,
        chairCovers: true,
      },
    },
    {
      date: "6/9/2025",
      days: 1,
      name: "Vishnu raj",
      address: "Behind court, Anekal, Bangalore",
      phone: "8892364643",
      alternative_phone: "9448735823",
      event_type: "Namakarna",
      religion: "Hindu",
      timings: "10:00 AM to 6:00PM",
      services: {
        hallRent: true,
        cookingUtensils: false,
        mantap: false,
        darbarChairs: true,
        cleaningLabour: true,
        deepaLamps: false,
        orchestraStage: false,
        dolStage: true,
        peta: false,
        redCarpet: true,
        micSet: true,
        decorPlants: true,
        godStatues: false,
        holigeDosaStove: false,
        lightDecoration: true,
        roadCuttingSerialSet: true,
        lightMusic: true,
        hasemani: false,
        speakers: true,
        chairCovers: true,
      },
    },
    {
      date: "7/9/2025",
      days: 1,
      name: "Devi Verma",
      address: "jigani, Anekal, Bangalore",
      phone: "8892364643",
      alternative_phone: "9448735823",
      event_type: "Badoota",
      religion: "Hindu",
      timings: "10:00 AM to 6:00PM",
      services: {
        hallRent: true,
        cookingUtensils: false,
        mantap: false,
        darbarChairs: true,
        cleaningLabour: true,
        deepaLamps: false,
        orchestraStage: false,
        dolStage: true,
        peta: false,
        redCarpet: true,
        micSet: true,
        decorPlants: true,
        godStatues: false,
        holigeDosaStove: false,
        lightDecoration: true,
        roadCuttingSerialSet: true,
        lightMusic: true,
        hasemani: false,
        speakers: true,
        chairCovers: true,
      },
    },
    {
      date: "18/10/2025",
      days: 1,
      name: "Shamili",
      address: "gowrenahalli, Anekal, Bangalore",
      phone: "8892364643",
      alternative_phone: "9448735823",
      event_type: "Birthday",
      religion: "Hindu",
      timings: "10:00 AM to 6:00PM",
      services: {
        hallRent: true,
        cookingUtensils: false,
        mantap: false,
        darbarChairs: true,
        cleaningLabour: true,
        deepaLamps: false,
        orchestraStage: false,
        dolStage: true,
        peta: false,
        redCarpet: true,
        micSet: true,
        decorPlants: true,
        godStatues: false,
        holigeDosaStove: false,
        lightDecoration: true,
        roadCuttingSerialSet: true,
        lightMusic: true,
        hasemani: false,
        speakers: true,
        chairCovers: true,
      },
    },
    {
      date: "30/8/2025",
      days: 2,
      name: "Poojarappa",
      address: "Kadshivannahalli, Anekal, Bangalore",
      phone: "8892364643",
      alternative_phone: "9448735823",
      event_type: "Wedding",
      religion: "Hindu",
      timings: "6:00 PM to 6:00PM",
      services: {
        hallRent: true,
        cookingUtensils: false,
        mantap: false,
        darbarChairs: true,
        cleaningLabour: true,
        deepaLamps: false,
        orchestraStage: false,
        dolStage: true,
        peta: false,
        redCarpet: true,
        micSet: true,
        decorPlants: true,
        godStatues: false,
        holigeDosaStove: false,
        lightDecoration: true,
        roadCuttingSerialSet: true,
        lightMusic: true,
        hasemani: false,
        speakers: true,
        chairCovers: true,
      },
    },
    {
      date: "30/8/2025",
      days: 1,
      name: "Joseph",
      address: "Newpet, Anekal, Bangalore",
      phone: "8892364643",
      alternative_phone: "9448735823",
      event_type: "Prayer meet",
      religion: "Other",
      timings: "8:00 AM to 6:00PM",
      services: {
        hallRent: true,
        cookingUtensils: false,
        mantap: false,
        darbarChairs: true,
        cleaningLabour: true,
        deepaLamps: false,
        orchestraStage: false,
        dolStage: true,
        peta: false,
        redCarpet: true,
        micSet: true,
        decorPlants: true,
        godStatues: false,
        holigeDosaStove: false,
        lightDecoration: true,
        roadCuttingSerialSet: true,
        lightMusic: true,
        hasemani: false,
        speakers: true,
        chairCovers: true,
      },
    },
  ];

  export const expenses = [
    { date: "01/08/2025", category: "Repair", amount: 5000, description: "AC Repair" },
    { date: "05/08/2025", category: "Purchase", amount: 15000, description: "Bought new chairs" },
    { date: "15/08/2025", category: "Loan Payment", amount: 20000, description: "Paid loan EMI" },
    { date: "20/08/2025", category: "Borrower Payment", amount: 7000, description: "Paid to borrower" },
  ];

  export const RELIGION_COLORS = {
    Hindu: "#FF9800",     // orange
    Muslim: "#4CAF50",    // green
    Others: "#03A9F4",    // sky blue
  };